[cr139][MacOS] IOMasterPort has been deprecated in MacOS 12.0.
 ../../brave/browser/brave_ads/device_id/device_id_impl_mac.cc:199:26: error: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Werror,-Wdeprecated-declarations]
   199 |   kern_return_t result = IOMasterPort(MACH_PORT_NULL, &main_port);
       |                          ^~~~~~~~~~~~
       |                          kIOMainPortDefault
 ../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
   143 | IOMasterPort( mach_port_t       bootstrapPort,
       | ^
 1 error generated.

Chromium change:
https://chromium.googlesource.com/chromium/src/+/cb3ea77719c5f410c7317b7aa6a580379138632c

commit cb3ea77719c5f410c7317b7aa6a580379138632c
Author: Avi Drissman <avi@chromium.org>
Date:   Wed May 28 09:48:43 2025 -0700

    Change Chromium's deployment target to macOS 12

    This is the minimal set of changes needed to switch the deployment
    target to macOS 12, specifically ones that address deprecation
    warnings (which are errors).

    Further cleanup will follow.

    Bug: 408364834, 40250210